// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbslxssxkxgugwkjnlqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFic2x4c3N4a3hndWd3a2pubHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0OTQ4MDksImV4cCI6MjA4OTA3MDgwOX0.Ke3Hh71BP5kppgVYZYOf5mxvCAu2j4iDqek8UuNM4YU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});